version: "3"

# NOTE: .env variables are available to this file at build time
# NOTE: .env variables are made available to containers at runtime (through 'env_file' option)
# NOTE: build time container variables must be explicitly passed to the container using the 'args' option

services:
  graphite:
    image: graphiteapp/graphite-statsd

    container_name: graphite
    env_file:
      - ./.env
    ports:
      - 8125:8125/udp
      - 8888:80
    restart: always

  prometheus:
    build:
      context: .
      dockerfile: ./deployment/prometheus/Dockerfile 
    env_file:
      - ./.env
    restart: always
    
  grafana:
    build:
      context: .
      dockerfile: ./deployment/grafana/Dockerfile 
    env_file:
      - ./.env
    links:
      - prometheus
      - graphite
    restart: always
    
  rabbitmq:
    build:
      context: .
      args:
        DEBUG: ${DEBUG}
      dockerfile: ./deployment/rabbitmq/Dockerfile 
    env_file:
      - ./.env
    restart: always

  webapp:  
    build:
      context: .
      args:
        DEBUG: ${DEBUG}
        SRC_DEPLOY_PATH: ${SRC_DEPLOY_PATH}
      dockerfile: ./deployment/webapp/Dockerfile 
    env_file:
      - ./.env
    links:
      - rabbitmq
      - graphite
    command:
      sh /webapp.sh
    restart: always

  nginx:  
    build:
      context: .
      args:
        DEBUG: ${DEBUG}
      dockerfile: ./deployment/nginx/Dockerfile 
    env_file:
      - ./.env
    ports:
      - "${APP_PORT_HTTP}:80"
      - "${APP_PORT_HTTPS}:443"
      - 5672:5672
    links:
      - rabbitmq
      - grafana
      - prometheus
    command:
      sh /nginx.sh
    restart: always

  pyronix:  
    build:
      context: .
      args:
        DEBUG: ${DEBUG}
        SRC_DEPLOY_PATH: ${SRC_DEPLOY_PATH}
      dockerfile: ./deployment/pyronix/Dockerfile 
    env_file:
      - ./.env
    command:
      sh /pyronix.sh
    restart: always

