# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

  - name: Graphite
    orgId: 2

# list of datasources to insert/update depending
# whats available in the database
datasources:
  - name: Graphite
    orgId: 1
    type: graphite
    access: proxy
    url: http://graphite:8080
    jsonData:
      graphiteVersion: "1.1"

  - name: Prometheus
    orgId: 1
    type: prometheus
    access: proxy
    url: http://prometheus:9090